# Example configuration for ESPHome E1.31 Light Component

# Basic configuration
esphome:
  name: e131_light_controller
  platform: ESP32
  board: esp32dev

# External component configuration
external_components:
  - source:
      type: git
      url: https://github.com/SparkyDan555/ESPHome-SACN
      ref: main
    components: [ e131_light ]

# Network configuration
wifi:
  ssid: "your_wifi_ssid"
  password: "your_wifi_password"

# E1.31 component configuration
e131_light:
  id: e131_light_device
  method: multicast  # or unicast
  port: 5568

# Example 1: RGBW Strip (Addressable)
light:
  - platform: neopixelbus
    id: rgbw_strip
    num_leds: 100
    type: GRBW
    variant: WS2812
    pin: GPIO23
    effects:
      - e131_light_addressable:
          e131_light_id: e131_light_device
          universe: 1
          start_address: 1
          channels: RGBW

# Example 2: RGB Strip (Addressable)
light:
  - platform: neopixelbus
    id: rgb_strip
    num_leds: 150
    type: GRB
    variant: WS2812
    pin: GPIO22
    effects:
      - e131_light_addressable:
          e131_light_id: e131_light_device
          universe: 2
          start_address: 1
          channels: RGB

# Example 3: Single Channel Light (Regular)
light:
  - platform: monochromatic
    id: single_channel
    output: gpio_output
    effects:
      - e131_light:
          e131_light_id: e131_light_device
          universe: 3
          start_address: 1
          channels: MONO

# GPIO output for single channel light
output:
  - platform: gpio
    id: gpio_output
    pin: GPIO21

# Example 4: RGBWW Spotlight (Regular)
light:
  - platform: rgbww
    id: rgbww_spotlight
    red: red_output
    green: green_output
    blue: blue_output
    cold_white: cold_output
    warm_white: warm_output
    cold_white_color_temperature: 6000 Kelvin
    warm_white_color_temperature: 3000 Kelvin
    effects:
      - e131_light:
          e131_light_id: e131_light_device
          universe: 4
          start_address: 1
          channels: RGB

# Example 5: Multiple Universes on One Strip (Addressable)
light:
  - platform: neopixelbus
    id: multi_universe_strip
    num_leds: 200
    type: GRB
    variant: WS2812
    pin: GPIO19
    effects:
      - e131_light_addressable:
          e131_light_id: e131_light_device
          universe: 5
          start_address: 1
          channels: RGB
      - e131_light_addressable:
          e131_light_id: e131_light_device
          universe: 6
          start_address: 151
          channels: RGB

# Example 6: Unicast Configuration
e131_light:
  id: e131_light_unicast
  method: unicast
  port: 5568

light:
  - platform: neopixelbus
    id: unicast_strip
    num_leds: 50
    type: GRB
    variant: WS2812
    pin: GPIO18
    effects:
      - e131_light_addressable:
          e131_light_id: e131_light_unicast
          universe: 7
          start_address: 1
          channels: RGB 